//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuSatisOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisId { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public int Tutar { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Durum { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
